import type { Locale } from "@/lib/i18n/config";

/**
 * The words on the marketplace pages — search, results, venue, checkout,
 * confirmation — in the site's eleven languages.
 *
 * Here rather than in the site dictionaries because those are the pitch to
 * venues, read by owners; these are read by guests booking a room, and change
 * on a different rhythm. `{name}` placeholders are filled by `fill()` in
 * stays-format.ts. Pairs ending 1 / N are the singular and the rest; languages
 * without plurals give the same word twice.
 *
 * Written without a native speaker for every language — plain and literal on
 * purpose, and worth a read before the marketplace is announced.
 */

const en = {
  navStays: "Find a Stay",
  heroEyebrow: "Book direct",
  heroTitle: "Find a place to stay",
  heroLede: "Independent stays across Thailand, booked directly with the people who run them. No booking fees.",
  where: "Where",
  wherePlaceholder: "City, area or place name",
  checkIn: "Check-in",
  checkOut: "Check-out",
  guests: "Guests",
  adults: "Adults",
  children: "Children",
  childrenHint: "Ages 0–17",
  rooms: "Rooms",
  done: "Done",
  search: "Search",
  adult1: "{n} adult",
  adultN: "{n} adults",
  child1: "{n} child",
  childN: "{n} children",
  room1: "{n} room",
  roomN: "{n} rooms",
  night1: "{n} night",
  nightN: "{n} nights",
  review1: "{n} review",
  reviewN: "{n} reviews",
  place1: "{n} place to stay",
  placeN: "{n} places to stay",
  resultsIn: "Stays in {place}",
  resultsAll: "Stays across Thailand",
  sortBy: "Sort by",
  sortRecommended: "Recommended",
  sortPrice: "Lowest price",
  sortRating: "Top rated",
  filters: "Filters",
  filterPrice: "Price per night",
  anyPrice: "Any price",
  upTo: "Up to {amount}",
  filterRating: "Guest rating",
  anyRating: "Any",
  ratingAtLeast: "{n}+",
  filterOptions: "Options",
  apply: "Apply",
  clear: "Clear",
  perNight: "per night",
  totalFor: "{amount} for {nights}",
  onlyLeft: "Only {n} left",
  seeAvailability: "See Availability",
  noRooms: "No rooms for your dates",
  noResults: "No stays match your search. Try other dates or a nearby place.",
  photoMissing: "No photo yet",
  overview: "Overview",
  about: "About",
  amenities: "Amenities",
  policies: "Policies",
  roomsTitle: "Choose your room",
  checkInFrom: "Check-in from {time}",
  checkOutBy: "Check-out by {time}",
  sleeps: "Sleeps {n}",
  sizeSqm: "{n} m²",
  yourChoices: "Your choices",
  priceFor: "Price for {nights}",
  breakfastIncluded: "Breakfast included",
  roomOnly: "Room only",
  freeCancelUntil: "Free cancellation until {date}",
  nonRefundable: "Non-refundable",
  freeCancellation: "Free cancellation",
  reserve: "Reserve",
  unavailable: "Not available for your dates",
  tooSmall: "Too small for your party",
  addDates: "Add your dates to see prices and availability.",
  update: "Update",
  contactTitle: "Book directly with {venue}",
  contactLede: "Rather talk first? Contact the venue — they answer their own phone.",
  call: "Call",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "Email",
  payAtProperty: "Pay at the property",
  payLater: "Online payment isn't available yet. You pay {venue} when you arrive.",
  checkoutTitle: "Your Booking",
  guestDetails: "Who's staying",
  fullName: "Full name",
  phone: "Phone",
  phoneHint: "With the country code, so the venue can reach you.",
  requests: "Special requests",
  requestsHint: "Optional. The venue will do what it can.",
  confirm: "Confirm Booking",
  confirming: "Booking…",
  summary: "Your stay",
  total: "Total",
  dueNow: "Due now",
  dueAtProperty: "Due at the property",
  agree: "By confirming, you agree to this rate's cancellation terms. Your details go to {venue} for this booking only.",
  confirmedTitle: "Booking confirmed",
  confirmedLede: "The details are on their way to {email}. Show the reference when you arrive.",
  reference: "Reference",
  cancelled: "This booking has been cancelled.",
  anotherStay: "Find Another Stay",
  bookingMissing: "We couldn't find that booking. Check the link in your confirmation email.",
  backToResults: "All stays",
  cancelBooking: "Cancel Booking",
  cancelWarning: "The room goes back on sale and this cannot be undone. Nothing has been charged.",
  cancelYes: "Yes, Cancel It",
  cannotCancel: "This rate can no longer be cancelled online. Contact {venue} to change your booking.",
  cancelledByYou: "You cancelled this booking. Nothing was charged.",
  cancelledByVenue: "{venue} cancelled this booking. Contact them if you did not expect it.",
};

export type StaysText = typeof en;

const th: StaysText = {
  navStays: "หาที่พัก",
  heroEyebrow: "จองตรง",
  heroTitle: "หาที่พักของคุณ",
  heroLede: "ที่พักอิสระทั่วประเทศไทย จองตรงกับเจ้าของที่ดูแลเอง ไม่มีค่าธรรมเนียมการจอง",
  where: "ที่ไหน",
  wherePlaceholder: "เมือง พื้นที่ หรือชื่อสถานที่",
  checkIn: "เช็กอิน",
  checkOut: "เช็กเอาต์",
  guests: "ผู้เข้าพัก",
  adults: "ผู้ใหญ่",
  children: "เด็ก",
  childrenHint: "อายุ 0–17 ปี",
  rooms: "ห้อง",
  done: "เสร็จสิ้น",
  search: "ค้นหา",
  adult1: "ผู้ใหญ่ {n} คน",
  adultN: "ผู้ใหญ่ {n} คน",
  child1: "เด็ก {n} คน",
  childN: "เด็ก {n} คน",
  room1: "{n} ห้อง",
  roomN: "{n} ห้อง",
  night1: "{n} คืน",
  nightN: "{n} คืน",
  review1: "{n} รีวิว",
  reviewN: "{n} รีวิว",
  place1: "ที่พัก {n} แห่ง",
  placeN: "ที่พัก {n} แห่ง",
  resultsIn: "ที่พักใน {place}",
  resultsAll: "ที่พักทั่วประเทศไทย",
  sortBy: "เรียงตาม",
  sortRecommended: "แนะนำ",
  sortPrice: "ราคาต่ำสุด",
  sortRating: "คะแนนสูงสุด",
  filters: "ตัวกรอง",
  filterPrice: "ราคาต่อคืน",
  anyPrice: "ทุกราคา",
  upTo: "ไม่เกิน {amount}",
  filterRating: "คะแนนจากผู้เข้าพัก",
  anyRating: "ทั้งหมด",
  ratingAtLeast: "{n}+",
  filterOptions: "ตัวเลือก",
  apply: "ใช้ตัวกรอง",
  clear: "ล้าง",
  perNight: "ต่อคืน",
  totalFor: "{amount} สำหรับ {nights}",
  onlyLeft: "เหลือเพียง {n} ห้อง",
  seeAvailability: "ดูห้องว่าง",
  noRooms: "ไม่มีห้องว่างในวันที่เลือก",
  noResults: "ไม่พบที่พักที่ตรงกับการค้นหา ลองเปลี่ยนวันหรือสถานที่ใกล้เคียง",
  photoMissing: "ยังไม่มีรูป",
  overview: "ภาพรวม",
  about: "เกี่ยวกับที่พัก",
  amenities: "สิ่งอำนวยความสะดวก",
  policies: "นโยบาย",
  roomsTitle: "เลือกห้องพัก",
  checkInFrom: "เช็กอินตั้งแต่ {time}",
  checkOutBy: "เช็กเอาต์ภายใน {time}",
  sleeps: "พักได้ {n} คน",
  sizeSqm: "{n} ตร.ม.",
  yourChoices: "ตัวเลือกของคุณ",
  priceFor: "ราคาสำหรับ {nights}",
  breakfastIncluded: "รวมอาหารเช้า",
  roomOnly: "เฉพาะห้องพัก",
  freeCancelUntil: "ยกเลิกฟรีถึง {date}",
  nonRefundable: "ไม่สามารถคืนเงินได้",
  freeCancellation: "ยกเลิกฟรี",
  reserve: "จอง",
  unavailable: "ไม่ว่างในวันที่เลือก",
  tooSmall: "ห้องเล็กเกินไปสำหรับจำนวนผู้เข้าพัก",
  addDates: "เลือกวันที่เพื่อดูราคาและห้องว่าง",
  update: "อัปเดต",
  contactTitle: "จองตรงกับ {venue}",
  contactLede: "อยากคุยก่อน? ติดต่อที่พักได้โดยตรง",
  call: "โทร",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "อีเมล",
  payAtProperty: "ชำระเงินที่ที่พัก",
  payLater: "ยังไม่รองรับการชำระเงินออนไลน์ คุณชำระเงินกับ {venue} เมื่อเข้าพัก",
  checkoutTitle: "การจองของคุณ",
  guestDetails: "ข้อมูลผู้เข้าพัก",
  fullName: "ชื่อ-นามสกุล",
  phone: "โทรศัพท์",
  phoneHint: "ใส่รหัสประเทศ เพื่อให้ที่พักติดต่อคุณได้",
  requests: "คำขอพิเศษ",
  requestsHint: "ไม่บังคับ ที่พักจะพยายามจัดให้",
  confirm: "ยืนยันการจอง",
  confirming: "กำลังจอง…",
  summary: "การเข้าพักของคุณ",
  total: "ยอดรวม",
  dueNow: "ชำระตอนนี้",
  dueAtProperty: "ชำระที่ที่พัก",
  agree: "เมื่อยืนยัน คุณยอมรับเงื่อนไขการยกเลิกของราคานี้ ข้อมูลของคุณจะส่งให้ {venue} สำหรับการจองนี้เท่านั้น",
  confirmedTitle: "ยืนยันการจองแล้ว",
  confirmedLede: "เราได้ส่งรายละเอียดไปที่ {email} แล้ว แสดงหมายเลขการจองเมื่อเข้าพัก",
  reference: "หมายเลขการจอง",
  cancelled: "การจองนี้ถูกยกเลิกแล้ว",
  anotherStay: "หาที่พักอื่น",
  bookingMissing: "ไม่พบการจองนี้ ตรวจสอบลิงก์ในอีเมลยืนยันของคุณ",
  backToResults: "ที่พักทั้งหมด",
  cancelBooking: "ยกเลิกการจอง",
  cancelWarning: "ห้องจะถูกเปิดขายอีกครั้งและไม่สามารถย้อนกลับได้ ยังไม่มีการเรียกเก็บเงินใด ๆ",
  cancelYes: "ใช่ ยกเลิกเลย",
  cannotCancel: "ราคานี้ไม่สามารถยกเลิกออนไลน์ได้แล้ว ติดต่อ {venue} เพื่อเปลี่ยนแปลงการจอง",
  cancelledByYou: "คุณยกเลิกการจองนี้แล้ว ไม่มีการเรียกเก็บเงิน",
  cancelledByVenue: "{venue} ได้ยกเลิกการจองนี้ หากไม่คาดคิด โปรดติดต่อที่พัก",
};

const zh: StaysText = {
  navStays: "查找住宿",
  heroEyebrow: "直接预订",
  heroTitle: "查找住宿",
  heroLede: "泰国各地的独立住宿，直接向经营者预订，无预订费。",
  where: "目的地",
  wherePlaceholder: "城市、区域或地名",
  checkIn: "入住",
  checkOut: "退房",
  guests: "住客",
  adults: "成人",
  children: "儿童",
  childrenHint: "0–17 岁",
  rooms: "客房",
  done: "完成",
  search: "搜索",
  adult1: "{n} 位成人",
  adultN: "{n} 位成人",
  child1: "{n} 位儿童",
  childN: "{n} 位儿童",
  room1: "{n} 间客房",
  roomN: "{n} 间客房",
  night1: "{n} 晚",
  nightN: "{n} 晚",
  review1: "{n} 条点评",
  reviewN: "{n} 条点评",
  place1: "{n} 处住宿",
  placeN: "{n} 处住宿",
  resultsIn: "{place}的住宿",
  resultsAll: "泰国各地的住宿",
  sortBy: "排序",
  sortRecommended: "推荐",
  sortPrice: "价格最低",
  sortRating: "评分最高",
  filters: "筛选",
  filterPrice: "每晚价格",
  anyPrice: "不限价格",
  upTo: "最高 {amount}",
  filterRating: "住客评分",
  anyRating: "不限",
  ratingAtLeast: "{n}+",
  filterOptions: "选项",
  apply: "应用",
  clear: "清除",
  perNight: "每晚",
  totalFor: "{nights}共 {amount}",
  onlyLeft: "仅剩 {n} 间",
  seeAvailability: "查看空房",
  noRooms: "所选日期无空房",
  noResults: "没有符合条件的住宿。请尝试其他日期或附近地点。",
  photoMissing: "暂无照片",
  overview: "概览",
  about: "简介",
  amenities: "设施",
  policies: "政策",
  roomsTitle: "选择客房",
  checkInFrom: "{time} 起可入住",
  checkOutBy: "{time} 前退房",
  sleeps: "可住 {n} 人",
  sizeSqm: "{n} 平方米",
  yourChoices: "您的选择",
  priceFor: "{nights}价格",
  breakfastIncluded: "含早餐",
  roomOnly: "仅客房",
  freeCancelUntil: "{date} 前免费取消",
  nonRefundable: "不可退款",
  freeCancellation: "免费取消",
  reserve: "预订",
  unavailable: "所选日期不可订",
  tooSmall: "无法容纳您的人数",
  addDates: "选择日期以查看价格和空房。",
  update: "更新",
  contactTitle: "直接向{venue}预订",
  contactLede: "想先沟通？直接联系住宿方。",
  call: "电话",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "邮件",
  payAtProperty: "到店付款",
  payLater: "暂不支持在线付款。入住时向{venue}付款。",
  checkoutTitle: "您的预订",
  guestDetails: "入住人信息",
  fullName: "姓名",
  phone: "电话",
  phoneHint: "请填写国家区号，以便住宿方联系您。",
  requests: "特殊要求",
  requestsHint: "选填。住宿方会尽量安排。",
  confirm: "确认预订",
  confirming: "正在预订…",
  summary: "您的行程",
  total: "总价",
  dueNow: "现在支付",
  dueAtProperty: "到店支付",
  agree: "确认即表示您同意该价格的取消条款。您的信息仅提供给{venue}用于本次预订。",
  confirmedTitle: "预订已确认",
  confirmedLede: "详情已发送至 {email}。入住时请出示预订编号。",
  reference: "预订编号",
  cancelled: "此预订已取消。",
  anotherStay: "查找其他住宿",
  bookingMissing: "找不到该预订。请检查确认邮件中的链接。",
  backToResults: "所有住宿",
  cancelBooking: "取消预订",
  cancelWarning: "客房将重新开放预订，且无法撤销。目前未收取任何费用。",
  cancelYes: "确认取消",
  cannotCancel: "该价格已无法在线取消。如需更改预订，请联系{venue}。",
  cancelledByYou: "您已取消此预订，未收取任何费用。",
  cancelledByVenue: "{venue}已取消此预订。如有疑问，请联系住宿方。",
};

const ja: StaysText = {
  navStays: "宿を探す",
  heroEyebrow: "直接予約",
  heroTitle: "宿を探す",
  heroLede: "タイ各地の個性ある宿を、運営者に直接予約。予約手数料はかかりません。",
  where: "行き先",
  wherePlaceholder: "都市、エリア、地名",
  checkIn: "チェックイン",
  checkOut: "チェックアウト",
  guests: "宿泊者",
  adults: "大人",
  children: "子ども",
  childrenHint: "0〜17歳",
  rooms: "部屋",
  done: "完了",
  search: "検索",
  adult1: "大人 {n} 名",
  adultN: "大人 {n} 名",
  child1: "子ども {n} 名",
  childN: "子ども {n} 名",
  room1: "{n} 室",
  roomN: "{n} 室",
  night1: "{n} 泊",
  nightN: "{n} 泊",
  review1: "口コミ {n} 件",
  reviewN: "口コミ {n} 件",
  place1: "{n} 件の宿",
  placeN: "{n} 件の宿",
  resultsIn: "{place}の宿",
  resultsAll: "タイ全土の宿",
  sortBy: "並べ替え",
  sortRecommended: "おすすめ",
  sortPrice: "料金の安い順",
  sortRating: "評価の高い順",
  filters: "絞り込み",
  filterPrice: "1泊あたりの料金",
  anyPrice: "指定なし",
  upTo: "{amount} まで",
  filterRating: "宿泊者の評価",
  anyRating: "指定なし",
  ratingAtLeast: "{n}+",
  filterOptions: "条件",
  apply: "適用",
  clear: "クリア",
  perNight: "1泊",
  totalFor: "{nights}で {amount}",
  onlyLeft: "残り {n} 室",
  seeAvailability: "空室を見る",
  noRooms: "選択した日程に空室はありません",
  noResults: "条件に合う宿がありません。日程や近くの地名を変えてお試しください。",
  photoMissing: "写真はまだありません",
  overview: "概要",
  about: "宿について",
  amenities: "設備・サービス",
  policies: "ポリシー",
  roomsTitle: "部屋を選ぶ",
  checkInFrom: "チェックイン {time} から",
  checkOutBy: "チェックアウト {time} まで",
  sleeps: "定員 {n} 名",
  sizeSqm: "{n} m²",
  yourChoices: "プラン",
  priceFor: "{nights}の料金",
  breakfastIncluded: "朝食付き",
  roomOnly: "素泊まり",
  freeCancelUntil: "{date} まで無料キャンセル",
  nonRefundable: "返金不可",
  freeCancellation: "無料キャンセル",
  reserve: "予約する",
  unavailable: "選択した日程では予約できません",
  tooSmall: "人数に対して部屋が小さすぎます",
  addDates: "日程を入れると料金と空室が表示されます。",
  update: "更新",
  contactTitle: "{venue}に直接予約",
  contactLede: "先に相談したい場合は、宿に直接ご連絡ください。",
  call: "電話",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "メール",
  payAtProperty: "現地払い",
  payLater: "オンライン決済はまだご利用いただけません。到着時に{venue}へお支払いください。",
  checkoutTitle: "ご予約内容",
  guestDetails: "宿泊者情報",
  fullName: "氏名",
  phone: "電話番号",
  phoneHint: "宿から連絡できるよう、国番号から入力してください。",
  requests: "リクエスト",
  requestsHint: "任意。できる限り対応します。",
  confirm: "予約を確定する",
  confirming: "予約中…",
  summary: "ご滞在",
  total: "合計",
  dueNow: "今すぐ支払う",
  dueAtProperty: "現地で支払う",
  agree: "確定すると、このプランのキャンセル条件に同意したものとみなされます。お客様の情報はこの予約のためにのみ{venue}へ送られます。",
  confirmedTitle: "予約が確定しました",
  confirmedLede: "詳細を {email} にお送りしました。到着時に予約番号をご提示ください。",
  reference: "予約番号",
  cancelled: "この予約はキャンセルされました。",
  anotherStay: "別の宿を探す",
  bookingMissing: "予約が見つかりません。確認メールのリンクをご確認ください。",
  backToResults: "すべての宿",
  cancelBooking: "予約をキャンセル",
  cancelWarning: "部屋は再び販売され、元に戻せません。料金は発生していません。",
  cancelYes: "キャンセルする",
  cannotCancel: "このプランはオンラインでキャンセルできなくなりました。変更は{venue}にご連絡ください。",
  cancelledByYou: "この予約はキャンセルされました。料金は発生していません。",
  cancelledByVenue: "{venue}がこの予約をキャンセルしました。心当たりがない場合は宿にご連絡ください。",
};

const ko: StaysText = {
  navStays: "숙소 찾기",
  heroEyebrow: "직접 예약",
  heroTitle: "숙소 찾기",
  heroLede: "태국 곳곳의 개성 있는 숙소를 운영자에게 직접 예약하세요. 예약 수수료가 없습니다.",
  where: "목적지",
  wherePlaceholder: "도시, 지역 또는 장소 이름",
  checkIn: "체크인",
  checkOut: "체크아웃",
  guests: "투숙객",
  adults: "성인",
  children: "어린이",
  childrenHint: "0–17세",
  rooms: "객실",
  done: "완료",
  search: "검색",
  adult1: "성인 {n}명",
  adultN: "성인 {n}명",
  child1: "어린이 {n}명",
  childN: "어린이 {n}명",
  room1: "객실 {n}개",
  roomN: "객실 {n}개",
  night1: "{n}박",
  nightN: "{n}박",
  review1: "리뷰 {n}개",
  reviewN: "리뷰 {n}개",
  place1: "숙소 {n}곳",
  placeN: "숙소 {n}곳",
  resultsIn: "{place}의 숙소",
  resultsAll: "태국 전역의 숙소",
  sortBy: "정렬",
  sortRecommended: "추천순",
  sortPrice: "낮은 가격순",
  sortRating: "평점순",
  filters: "필터",
  filterPrice: "1박 요금",
  anyPrice: "전체 가격",
  upTo: "최대 {amount}",
  filterRating: "투숙객 평점",
  anyRating: "전체",
  ratingAtLeast: "{n}+",
  filterOptions: "옵션",
  apply: "적용",
  clear: "초기화",
  perNight: "1박",
  totalFor: "{nights} {amount}",
  onlyLeft: "{n}개 남음",
  seeAvailability: "객실 보기",
  noRooms: "선택한 날짜에 빈 객실이 없습니다",
  noResults: "검색과 일치하는 숙소가 없습니다. 다른 날짜나 가까운 장소로 검색해 보세요.",
  photoMissing: "사진 없음",
  overview: "개요",
  about: "숙소 소개",
  amenities: "편의 시설",
  policies: "정책",
  roomsTitle: "객실 선택",
  checkInFrom: "{time}부터 체크인",
  checkOutBy: "{time}까지 체크아웃",
  sleeps: "최대 {n}명",
  sizeSqm: "{n}m²",
  yourChoices: "요금 옵션",
  priceFor: "{nights} 요금",
  breakfastIncluded: "조식 포함",
  roomOnly: "객실만",
  freeCancelUntil: "{date}까지 무료 취소",
  nonRefundable: "환불 불가",
  freeCancellation: "무료 취소",
  reserve: "예약",
  unavailable: "선택한 날짜에 예약할 수 없음",
  tooSmall: "인원에 비해 객실이 작습니다",
  addDates: "날짜를 선택하면 요금과 빈 객실을 볼 수 있습니다.",
  update: "업데이트",
  contactTitle: "{venue}에 직접 예약",
  contactLede: "먼저 문의하고 싶으신가요? 숙소에 직접 연락하세요.",
  call: "전화",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "이메일",
  payAtProperty: "현장 결제",
  payLater: "온라인 결제는 아직 지원되지 않습니다. 도착 시 {venue}에 결제하세요.",
  checkoutTitle: "예약 정보",
  guestDetails: "투숙객 정보",
  fullName: "이름",
  phone: "전화번호",
  phoneHint: "숙소가 연락할 수 있도록 국가 번호를 포함해 입력하세요.",
  requests: "요청 사항",
  requestsHint: "선택 사항입니다. 숙소에서 최대한 반영합니다.",
  confirm: "예약 확정",
  confirming: "예약 중…",
  summary: "숙박 정보",
  total: "합계",
  dueNow: "지금 결제",
  dueAtProperty: "현장 결제",
  agree: "확정하면 이 요금의 취소 조건에 동의하게 됩니다. 정보는 이 예약을 위해서만 {venue}에 전달됩니다.",
  confirmedTitle: "예약이 확정되었습니다",
  confirmedLede: "{email}(으)로 상세 내용을 보냈습니다. 도착 시 예약 번호를 보여 주세요.",
  reference: "예약 번호",
  cancelled: "이 예약은 취소되었습니다.",
  anotherStay: "다른 숙소 찾기",
  bookingMissing: "예약을 찾을 수 없습니다. 확인 이메일의 링크를 확인하세요.",
  backToResults: "전체 숙소",
  cancelBooking: "예약 취소",
  cancelWarning: "객실이 다시 판매되며 되돌릴 수 없습니다. 결제된 금액은 없습니다.",
  cancelYes: "네, 취소합니다",
  cannotCancel: "이 요금은 더 이상 온라인으로 취소할 수 없습니다. 예약 변경은 {venue}에 문의하세요.",
  cancelledByYou: "예약을 취소했습니다. 결제된 금액은 없습니다.",
  cancelledByVenue: "{venue}에서 이 예약을 취소했습니다. 예상하지 못했다면 숙소에 문의하세요.",
};

const es: StaysText = {
  navStays: "Buscar alojamiento",
  heroEyebrow: "Reserva directa",
  heroTitle: "Encuentra dónde alojarte",
  heroLede: "Alojamientos independientes en toda Tailandia, reservados directamente con quienes los gestionan. Sin comisiones de reserva.",
  where: "Destino",
  wherePlaceholder: "Ciudad, zona o lugar",
  checkIn: "Entrada",
  checkOut: "Salida",
  guests: "Huéspedes",
  adults: "Adultos",
  children: "Niños",
  childrenHint: "De 0 a 17 años",
  rooms: "Habitaciones",
  done: "Listo",
  search: "Buscar",
  adult1: "{n} adulto",
  adultN: "{n} adultos",
  child1: "{n} niño",
  childN: "{n} niños",
  room1: "{n} habitación",
  roomN: "{n} habitaciones",
  night1: "{n} noche",
  nightN: "{n} noches",
  review1: "{n} reseña",
  reviewN: "{n} reseñas",
  place1: "{n} alojamiento",
  placeN: "{n} alojamientos",
  resultsIn: "Alojamientos en {place}",
  resultsAll: "Alojamientos en toda Tailandia",
  sortBy: "Ordenar por",
  sortRecommended: "Recomendados",
  sortPrice: "Precio más bajo",
  sortRating: "Mejor valorados",
  filters: "Filtros",
  filterPrice: "Precio por noche",
  anyPrice: "Cualquier precio",
  upTo: "Hasta {amount}",
  filterRating: "Valoración",
  anyRating: "Cualquiera",
  ratingAtLeast: "{n}+",
  filterOptions: "Opciones",
  apply: "Aplicar",
  clear: "Borrar",
  perNight: "por noche",
  totalFor: "{amount} por {nights}",
  onlyLeft: "Solo quedan {n}",
  seeAvailability: "Ver disponibilidad",
  noRooms: "No hay habitaciones para tus fechas",
  noResults: "Ningún alojamiento coincide. Prueba otras fechas o un lugar cercano.",
  photoMissing: "Aún sin foto",
  overview: "Resumen",
  about: "Descripción",
  amenities: "Servicios",
  policies: "Normas",
  roomsTitle: "Elige tu habitación",
  checkInFrom: "Entrada desde las {time}",
  checkOutBy: "Salida antes de las {time}",
  sleeps: "Para {n}",
  sizeSqm: "{n} m²",
  yourChoices: "Tus opciones",
  priceFor: "Precio por {nights}",
  breakfastIncluded: "Desayuno incluido",
  roomOnly: "Solo alojamiento",
  freeCancelUntil: "Cancelación gratuita hasta el {date}",
  nonRefundable: "No reembolsable",
  freeCancellation: "Cancelación gratuita",
  reserve: "Reservar",
  unavailable: "No disponible en tus fechas",
  tooSmall: "Demasiado pequeña para tu grupo",
  addDates: "Añade tus fechas para ver precios y disponibilidad.",
  update: "Actualizar",
  contactTitle: "Reserva directamente con {venue}",
  contactLede: "¿Prefieres hablar antes? Contacta con el alojamiento.",
  call: "Llamar",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "Correo",
  payAtProperty: "Pago en el alojamiento",
  payLater: "El pago en línea aún no está disponible. Pagas a {venue} cuando llegues.",
  checkoutTitle: "Tu reserva",
  guestDetails: "Quién se aloja",
  fullName: "Nombre completo",
  phone: "Teléfono",
  phoneHint: "Con el prefijo del país, para que el alojamiento pueda contactarte.",
  requests: "Peticiones especiales",
  requestsHint: "Opcional. El alojamiento hará lo posible.",
  confirm: "Confirmar reserva",
  confirming: "Reservando…",
  summary: "Tu estancia",
  total: "Total",
  dueNow: "A pagar ahora",
  dueAtProperty: "A pagar en el alojamiento",
  agree: "Al confirmar, aceptas las condiciones de cancelación de esta tarifa. Tus datos se envían a {venue} solo para esta reserva.",
  confirmedTitle: "Reserva confirmada",
  confirmedLede: "Hemos enviado los detalles a {email}. Muestra la referencia al llegar.",
  reference: "Referencia",
  cancelled: "Esta reserva se ha cancelado.",
  anotherStay: "Buscar otro alojamiento",
  bookingMissing: "No encontramos esa reserva. Revisa el enlace del correo de confirmación.",
  backToResults: "Todos los alojamientos",
  cancelBooking: "Cancelar reserva",
  cancelWarning: "La habitación vuelve a la venta y no se puede deshacer. No se ha cobrado nada.",
  cancelYes: "Sí, cancelar",
  cannotCancel: "Esta tarifa ya no se puede cancelar en línea. Contacta con {venue} para cambiar tu reserva.",
  cancelledByYou: "Has cancelado esta reserva. No se ha cobrado nada.",
  cancelledByVenue: "{venue} ha cancelado esta reserva. Contacta con el alojamiento si no lo esperabas.",
};

const fr: StaysText = {
  navStays: "Trouver un hébergement",
  heroEyebrow: "Réservation directe",
  heroTitle: "Trouvez où séjourner",
  heroLede: "Des hébergements indépendants dans toute la Thaïlande, réservés directement auprès de ceux qui les tiennent. Sans frais de réservation.",
  where: "Destination",
  wherePlaceholder: "Ville, quartier ou lieu",
  checkIn: "Arrivée",
  checkOut: "Départ",
  guests: "Voyageurs",
  adults: "Adultes",
  children: "Enfants",
  childrenHint: "De 0 à 17 ans",
  rooms: "Chambres",
  done: "Terminé",
  search: "Rechercher",
  adult1: "{n} adulte",
  adultN: "{n} adultes",
  child1: "{n} enfant",
  childN: "{n} enfants",
  room1: "{n} chambre",
  roomN: "{n} chambres",
  night1: "{n} nuit",
  nightN: "{n} nuits",
  review1: "{n} avis",
  reviewN: "{n} avis",
  place1: "{n} hébergement",
  placeN: "{n} hébergements",
  resultsIn: "Hébergements à {place}",
  resultsAll: "Hébergements dans toute la Thaïlande",
  sortBy: "Trier par",
  sortRecommended: "Recommandés",
  sortPrice: "Prix le plus bas",
  sortRating: "Mieux notés",
  filters: "Filtres",
  filterPrice: "Prix par nuit",
  anyPrice: "Tous les prix",
  upTo: "Jusqu'à {amount}",
  filterRating: "Note des voyageurs",
  anyRating: "Toutes",
  ratingAtLeast: "{n}+",
  filterOptions: "Options",
  apply: "Appliquer",
  clear: "Effacer",
  perNight: "par nuit",
  totalFor: "{amount} pour {nights}",
  onlyLeft: "Plus que {n}",
  seeAvailability: "Voir les disponibilités",
  noRooms: "Aucune chambre à vos dates",
  noResults: "Aucun hébergement ne correspond. Essayez d'autres dates ou un lieu proche.",
  photoMissing: "Pas encore de photo",
  overview: "Aperçu",
  about: "À propos",
  amenities: "Équipements",
  policies: "Conditions",
  roomsTitle: "Choisissez votre chambre",
  checkInFrom: "Arrivée à partir de {time}",
  checkOutBy: "Départ avant {time}",
  sleeps: "{n} personnes",
  sizeSqm: "{n} m²",
  yourChoices: "Vos options",
  priceFor: "Prix pour {nights}",
  breakfastIncluded: "Petit-déjeuner inclus",
  roomOnly: "Chambre seule",
  freeCancelUntil: "Annulation gratuite jusqu'au {date}",
  nonRefundable: "Non remboursable",
  freeCancellation: "Annulation gratuite",
  reserve: "Réserver",
  unavailable: "Indisponible à vos dates",
  tooSmall: "Trop petite pour votre groupe",
  addDates: "Ajoutez vos dates pour voir les prix et les disponibilités.",
  update: "Mettre à jour",
  contactTitle: "Réservez directement auprès de {venue}",
  contactLede: "Vous préférez en parler d'abord ? Contactez l'établissement.",
  call: "Appeler",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "E-mail",
  payAtProperty: "Paiement sur place",
  payLater: "Le paiement en ligne n'est pas encore disponible. Vous payez {venue} à votre arrivée.",
  checkoutTitle: "Votre réservation",
  guestDetails: "Qui séjourne",
  fullName: "Nom complet",
  phone: "Téléphone",
  phoneHint: "Avec l'indicatif du pays, pour que l'établissement puisse vous joindre.",
  requests: "Demandes particulières",
  requestsHint: "Facultatif. L'établissement fera son possible.",
  confirm: "Confirmer la réservation",
  confirming: "Réservation…",
  summary: "Votre séjour",
  total: "Total",
  dueNow: "À payer maintenant",
  dueAtProperty: "À payer sur place",
  agree: "En confirmant, vous acceptez les conditions d'annulation de ce tarif. Vos coordonnées sont transmises à {venue} pour cette réservation uniquement.",
  confirmedTitle: "Réservation confirmée",
  confirmedLede: "Les détails ont été envoyés à {email}. Présentez la référence à votre arrivée.",
  reference: "Référence",
  cancelled: "Cette réservation a été annulée.",
  anotherStay: "Trouver un autre hébergement",
  bookingMissing: "Réservation introuvable. Vérifiez le lien de votre e-mail de confirmation.",
  backToResults: "Tous les hébergements",
  cancelBooking: "Annuler la réservation",
  cancelWarning: "La chambre est remise en vente et cela ne peut pas être annulé. Rien n'a été débité.",
  cancelYes: "Oui, annuler",
  cannotCancel: "Ce tarif ne peut plus être annulé en ligne. Contactez {venue} pour modifier votre réservation.",
  cancelledByYou: "Vous avez annulé cette réservation. Rien n'a été débité.",
  cancelledByVenue: "{venue} a annulé cette réservation. Contactez l'établissement si vous ne vous y attendiez pas.",
};

const de: StaysText = {
  navStays: "Unterkunft finden",
  heroEyebrow: "Direkt buchen",
  heroTitle: "Finde deine Unterkunft",
  heroLede: "Unabhängige Unterkünfte in ganz Thailand, direkt bei den Menschen gebucht, die sie führen. Ohne Buchungsgebühren.",
  where: "Reiseziel",
  wherePlaceholder: "Stadt, Gegend oder Ort",
  checkIn: "Anreise",
  checkOut: "Abreise",
  guests: "Gäste",
  adults: "Erwachsene",
  children: "Kinder",
  childrenHint: "0–17 Jahre",
  rooms: "Zimmer",
  done: "Fertig",
  search: "Suchen",
  adult1: "{n} Erwachsener",
  adultN: "{n} Erwachsene",
  child1: "{n} Kind",
  childN: "{n} Kinder",
  room1: "{n} Zimmer",
  roomN: "{n} Zimmer",
  night1: "{n} Nacht",
  nightN: "{n} Nächte",
  review1: "{n} Bewertung",
  reviewN: "{n} Bewertungen",
  place1: "{n} Unterkunft",
  placeN: "{n} Unterkünfte",
  resultsIn: "Unterkünfte in {place}",
  resultsAll: "Unterkünfte in ganz Thailand",
  sortBy: "Sortieren nach",
  sortRecommended: "Empfohlen",
  sortPrice: "Niedrigster Preis",
  sortRating: "Beste Bewertung",
  filters: "Filter",
  filterPrice: "Preis pro Nacht",
  anyPrice: "Jeder Preis",
  upTo: "Bis {amount}",
  filterRating: "Gästebewertung",
  anyRating: "Alle",
  ratingAtLeast: "{n}+",
  filterOptions: "Optionen",
  apply: "Anwenden",
  clear: "Zurücksetzen",
  perNight: "pro Nacht",
  totalFor: "{amount} für {nights}",
  onlyLeft: "Nur noch {n}",
  seeAvailability: "Verfügbarkeit ansehen",
  noRooms: "Keine Zimmer an deinen Daten",
  noResults: "Keine passenden Unterkünfte. Versuche andere Daten oder einen Ort in der Nähe.",
  photoMissing: "Noch kein Foto",
  overview: "Überblick",
  about: "Über die Unterkunft",
  amenities: "Ausstattung",
  policies: "Richtlinien",
  roomsTitle: "Zimmer wählen",
  checkInFrom: "Check-in ab {time}",
  checkOutBy: "Check-out bis {time}",
  sleeps: "Für {n} Personen",
  sizeSqm: "{n} m²",
  yourChoices: "Deine Optionen",
  priceFor: "Preis für {nights}",
  breakfastIncluded: "Frühstück inklusive",
  roomOnly: "Nur Zimmer",
  freeCancelUntil: "Kostenlos stornierbar bis {date}",
  nonRefundable: "Nicht erstattbar",
  freeCancellation: "Kostenlose Stornierung",
  reserve: "Buchen",
  unavailable: "An deinen Daten nicht verfügbar",
  tooSmall: "Zu klein für deine Gruppe",
  addDates: "Gib deine Daten ein, um Preise und Verfügbarkeit zu sehen.",
  update: "Aktualisieren",
  contactTitle: "Direkt bei {venue} buchen",
  contactLede: "Lieber erst sprechen? Kontaktiere die Unterkunft direkt.",
  call: "Anrufen",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "E-Mail",
  payAtProperty: "Zahlung vor Ort",
  payLater: "Online-Zahlung ist noch nicht verfügbar. Du bezahlst {venue} bei der Ankunft.",
  checkoutTitle: "Deine Buchung",
  guestDetails: "Wer übernachtet",
  fullName: "Vollständiger Name",
  phone: "Telefon",
  phoneHint: "Mit Ländervorwahl, damit die Unterkunft dich erreichen kann.",
  requests: "Besondere Wünsche",
  requestsHint: "Optional. Die Unterkunft tut, was sie kann.",
  confirm: "Buchung bestätigen",
  confirming: "Wird gebucht…",
  summary: "Dein Aufenthalt",
  total: "Gesamt",
  dueNow: "Jetzt fällig",
  dueAtProperty: "Vor Ort fällig",
  agree: "Mit der Bestätigung akzeptierst du die Stornobedingungen dieses Tarifs. Deine Daten gehen nur für diese Buchung an {venue}.",
  confirmedTitle: "Buchung bestätigt",
  confirmedLede: "Die Details sind unterwegs an {email}. Zeig die Buchungsnummer bei der Ankunft.",
  reference: "Buchungsnummer",
  cancelled: "Diese Buchung wurde storniert.",
  anotherStay: "Andere Unterkunft finden",
  bookingMissing: "Buchung nicht gefunden. Prüfe den Link in deiner Bestätigungs-E-Mail.",
  backToResults: "Alle Unterkünfte",
  cancelBooking: "Buchung stornieren",
  cancelWarning: "Das Zimmer wird wieder angeboten, und das lässt sich nicht rückgängig machen. Es wurde nichts berechnet.",
  cancelYes: "Ja, stornieren",
  cannotCancel: "Dieser Tarif kann nicht mehr online storniert werden. Wende dich an {venue}, um deine Buchung zu ändern.",
  cancelledByYou: "Du hast diese Buchung storniert. Es wurde nichts berechnet.",
  cancelledByVenue: "{venue} hat diese Buchung storniert. Melde dich bei der Unterkunft, wenn du das nicht erwartet hast.",
};

const it: StaysText = {
  navStays: "Trova un alloggio",
  heroEyebrow: "Prenota diretto",
  heroTitle: "Trova dove soggiornare",
  heroLede: "Alloggi indipendenti in tutta la Thailandia, prenotati direttamente con chi li gestisce. Nessuna commissione di prenotazione.",
  where: "Destinazione",
  wherePlaceholder: "Città, zona o luogo",
  checkIn: "Check-in",
  checkOut: "Check-out",
  guests: "Ospiti",
  adults: "Adulti",
  children: "Bambini",
  childrenHint: "Da 0 a 17 anni",
  rooms: "Camere",
  done: "Fatto",
  search: "Cerca",
  adult1: "{n} adulto",
  adultN: "{n} adulti",
  child1: "{n} bambino",
  childN: "{n} bambini",
  room1: "{n} camera",
  roomN: "{n} camere",
  night1: "{n} notte",
  nightN: "{n} notti",
  review1: "{n} recensione",
  reviewN: "{n} recensioni",
  place1: "{n} alloggio",
  placeN: "{n} alloggi",
  resultsIn: "Alloggi a {place}",
  resultsAll: "Alloggi in tutta la Thailandia",
  sortBy: "Ordina per",
  sortRecommended: "Consigliati",
  sortPrice: "Prezzo più basso",
  sortRating: "Più votati",
  filters: "Filtri",
  filterPrice: "Prezzo a notte",
  anyPrice: "Qualsiasi prezzo",
  upTo: "Fino a {amount}",
  filterRating: "Voto degli ospiti",
  anyRating: "Qualsiasi",
  ratingAtLeast: "{n}+",
  filterOptions: "Opzioni",
  apply: "Applica",
  clear: "Cancella",
  perNight: "a notte",
  totalFor: "{amount} per {nights}",
  onlyLeft: "Solo {n} rimaste",
  seeAvailability: "Vedi disponibilità",
  noRooms: "Nessuna camera per le tue date",
  noResults: "Nessun alloggio corrisponde. Prova altre date o un luogo vicino.",
  photoMissing: "Ancora nessuna foto",
  overview: "Panoramica",
  about: "Descrizione",
  amenities: "Servizi",
  policies: "Condizioni",
  roomsTitle: "Scegli la camera",
  checkInFrom: "Check-in dalle {time}",
  checkOutBy: "Check-out entro le {time}",
  sleeps: "Per {n} persone",
  sizeSqm: "{n} m²",
  yourChoices: "Le tue opzioni",
  priceFor: "Prezzo per {nights}",
  breakfastIncluded: "Colazione inclusa",
  roomOnly: "Solo pernottamento",
  freeCancelUntil: "Cancellazione gratuita fino al {date}",
  nonRefundable: "Non rimborsabile",
  freeCancellation: "Cancellazione gratuita",
  reserve: "Prenota",
  unavailable: "Non disponibile per le tue date",
  tooSmall: "Troppo piccola per il tuo gruppo",
  addDates: "Inserisci le date per vedere prezzi e disponibilità.",
  update: "Aggiorna",
  contactTitle: "Prenota direttamente con {venue}",
  contactLede: "Preferisci parlarne prima? Contatta la struttura.",
  call: "Chiama",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "Email",
  payAtProperty: "Pagamento in struttura",
  payLater: "Il pagamento online non è ancora disponibile. Paghi {venue} all'arrivo.",
  checkoutTitle: "La tua prenotazione",
  guestDetails: "Chi soggiorna",
  fullName: "Nome e cognome",
  phone: "Telefono",
  phoneHint: "Con il prefisso internazionale, così la struttura può contattarti.",
  requests: "Richieste speciali",
  requestsHint: "Facoltativo. La struttura farà il possibile.",
  confirm: "Conferma prenotazione",
  confirming: "Prenotazione…",
  summary: "Il tuo soggiorno",
  total: "Totale",
  dueNow: "Da pagare ora",
  dueAtProperty: "Da pagare in struttura",
  agree: "Confermando accetti le condizioni di cancellazione di questa tariffa. I tuoi dati vanno a {venue} solo per questa prenotazione.",
  confirmedTitle: "Prenotazione confermata",
  confirmedLede: "Abbiamo inviato i dettagli a {email}. Mostra il codice all'arrivo.",
  reference: "Codice",
  cancelled: "Questa prenotazione è stata cancellata.",
  anotherStay: "Trova un altro alloggio",
  bookingMissing: "Prenotazione non trovata. Controlla il link nell'email di conferma.",
  backToResults: "Tutti gli alloggi",
  cancelBooking: "Cancella prenotazione",
  cancelWarning: "La camera torna in vendita e non si può annullare. Non è stato addebitato nulla.",
  cancelYes: "Sì, cancella",
  cannotCancel: "Questa tariffa non si può più cancellare online. Contatta {venue} per modificare la prenotazione.",
  cancelledByYou: "Hai cancellato questa prenotazione. Non è stato addebitato nulla.",
  cancelledByVenue: "{venue} ha cancellato questa prenotazione. Contatta la struttura se non te lo aspettavi.",
};

const pt: StaysText = {
  navStays: "Encontrar hospedagem",
  heroEyebrow: "Reserve direto",
  heroTitle: "Encontre onde ficar",
  heroLede: "Hospedagens independentes em toda a Tailândia, reservadas diretamente com quem as administra. Sem taxa de reserva.",
  where: "Destino",
  wherePlaceholder: "Cidade, região ou local",
  checkIn: "Check-in",
  checkOut: "Check-out",
  guests: "Hóspedes",
  adults: "Adultos",
  children: "Crianças",
  childrenHint: "De 0 a 17 anos",
  rooms: "Quartos",
  done: "Concluir",
  search: "Pesquisar",
  adult1: "{n} adulto",
  adultN: "{n} adultos",
  child1: "{n} criança",
  childN: "{n} crianças",
  room1: "{n} quarto",
  roomN: "{n} quartos",
  night1: "{n} noite",
  nightN: "{n} noites",
  review1: "{n} avaliação",
  reviewN: "{n} avaliações",
  place1: "{n} hospedagem",
  placeN: "{n} hospedagens",
  resultsIn: "Hospedagens em {place}",
  resultsAll: "Hospedagens em toda a Tailândia",
  sortBy: "Ordenar por",
  sortRecommended: "Recomendados",
  sortPrice: "Menor preço",
  sortRating: "Mais bem avaliados",
  filters: "Filtros",
  filterPrice: "Preço por noite",
  anyPrice: "Qualquer preço",
  upTo: "Até {amount}",
  filterRating: "Nota dos hóspedes",
  anyRating: "Qualquer",
  ratingAtLeast: "{n}+",
  filterOptions: "Opções",
  apply: "Aplicar",
  clear: "Limpar",
  perNight: "por noite",
  totalFor: "{amount} por {nights}",
  onlyLeft: "Só restam {n}",
  seeAvailability: "Ver disponibilidade",
  noRooms: "Sem quartos nas suas datas",
  noResults: "Nenhuma hospedagem encontrada. Tente outras datas ou um local próximo.",
  photoMissing: "Ainda sem foto",
  overview: "Visão geral",
  about: "Sobre",
  amenities: "Comodidades",
  policies: "Políticas",
  roomsTitle: "Escolha o quarto",
  checkInFrom: "Check-in a partir das {time}",
  checkOutBy: "Check-out até as {time}",
  sleeps: "Para {n} pessoas",
  sizeSqm: "{n} m²",
  yourChoices: "Suas opções",
  priceFor: "Preço por {nights}",
  breakfastIncluded: "Café da manhã incluído",
  roomOnly: "Só hospedagem",
  freeCancelUntil: "Cancelamento grátis até {date}",
  nonRefundable: "Não reembolsável",
  freeCancellation: "Cancelamento grátis",
  reserve: "Reservar",
  unavailable: "Indisponível nas suas datas",
  tooSmall: "Pequeno demais para o seu grupo",
  addDates: "Informe as datas para ver preços e disponibilidade.",
  update: "Atualizar",
  contactTitle: "Reserve direto com {venue}",
  contactLede: "Prefere conversar antes? Fale com a hospedagem.",
  call: "Ligar",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "E-mail",
  payAtProperty: "Pagamento na hospedagem",
  payLater: "O pagamento online ainda não está disponível. Você paga {venue} na chegada.",
  checkoutTitle: "Sua reserva",
  guestDetails: "Quem vai se hospedar",
  fullName: "Nome completo",
  phone: "Telefone",
  phoneHint: "Com o código do país, para a hospedagem poder falar com você.",
  requests: "Pedidos especiais",
  requestsHint: "Opcional. A hospedagem fará o possível.",
  confirm: "Confirmar reserva",
  confirming: "Reservando…",
  summary: "Sua estadia",
  total: "Total",
  dueNow: "A pagar agora",
  dueAtProperty: "A pagar na hospedagem",
  agree: "Ao confirmar, você aceita as condições de cancelamento desta tarifa. Seus dados vão para {venue} somente para esta reserva.",
  confirmedTitle: "Reserva confirmada",
  confirmedLede: "Enviamos os detalhes para {email}. Mostre o código na chegada.",
  reference: "Código",
  cancelled: "Esta reserva foi cancelada.",
  anotherStay: "Encontrar outra hospedagem",
  bookingMissing: "Reserva não encontrada. Confira o link no e-mail de confirmação.",
  backToResults: "Todas as hospedagens",
  cancelBooking: "Cancelar reserva",
  cancelWarning: "O quarto volta a ficar disponível e isso não pode ser desfeito. Nada foi cobrado.",
  cancelYes: "Sim, cancelar",
  cannotCancel: "Esta tarifa não pode mais ser cancelada online. Fale com {venue} para alterar sua reserva.",
  cancelledByYou: "Você cancelou esta reserva. Nada foi cobrado.",
  cancelledByVenue: "{venue} cancelou esta reserva. Fale com a hospedagem se não esperava por isso.",
};

const nl: StaysText = {
  navStays: "Verblijf zoeken",
  heroEyebrow: "Direct boeken",
  heroTitle: "Vind een verblijf",
  heroLede: "Onafhankelijke verblijven in heel Thailand, direct geboekt bij de mensen die ze runnen. Geen boekingskosten.",
  where: "Bestemming",
  wherePlaceholder: "Stad, gebied of plaats",
  checkIn: "Inchecken",
  checkOut: "Uitchecken",
  guests: "Gasten",
  adults: "Volwassenen",
  children: "Kinderen",
  childrenHint: "0–17 jaar",
  rooms: "Kamers",
  done: "Klaar",
  search: "Zoeken",
  adult1: "{n} volwassene",
  adultN: "{n} volwassenen",
  child1: "{n} kind",
  childN: "{n} kinderen",
  room1: "{n} kamer",
  roomN: "{n} kamers",
  night1: "{n} nacht",
  nightN: "{n} nachten",
  review1: "{n} review",
  reviewN: "{n} reviews",
  place1: "{n} verblijf",
  placeN: "{n} verblijven",
  resultsIn: "Verblijven in {place}",
  resultsAll: "Verblijven in heel Thailand",
  sortBy: "Sorteren op",
  sortRecommended: "Aanbevolen",
  sortPrice: "Laagste prijs",
  sortRating: "Best beoordeeld",
  filters: "Filters",
  filterPrice: "Prijs per nacht",
  anyPrice: "Elke prijs",
  upTo: "Tot {amount}",
  filterRating: "Gastbeoordeling",
  anyRating: "Alle",
  ratingAtLeast: "{n}+",
  filterOptions: "Opties",
  apply: "Toepassen",
  clear: "Wissen",
  perNight: "per nacht",
  totalFor: "{amount} voor {nights}",
  onlyLeft: "Nog maar {n}",
  seeAvailability: "Beschikbaarheid bekijken",
  noRooms: "Geen kamers op jouw data",
  noResults: "Geen verblijven gevonden. Probeer andere data of een plaats in de buurt.",
  photoMissing: "Nog geen foto",
  overview: "Overzicht",
  about: "Over het verblijf",
  amenities: "Voorzieningen",
  policies: "Voorwaarden",
  roomsTitle: "Kies je kamer",
  checkInFrom: "Inchecken vanaf {time}",
  checkOutBy: "Uitchecken vóór {time}",
  sleeps: "Voor {n} personen",
  sizeSqm: "{n} m²",
  yourChoices: "Jouw opties",
  priceFor: "Prijs voor {nights}",
  breakfastIncluded: "Ontbijt inbegrepen",
  roomOnly: "Alleen kamer",
  freeCancelUntil: "Gratis annuleren tot {date}",
  nonRefundable: "Niet restitueerbaar",
  freeCancellation: "Gratis annuleren",
  reserve: "Reserveren",
  unavailable: "Niet beschikbaar op jouw data",
  tooSmall: "Te klein voor je gezelschap",
  addDates: "Vul je data in om prijzen en beschikbaarheid te zien.",
  update: "Bijwerken",
  contactTitle: "Direct boeken bij {venue}",
  contactLede: "Liever eerst even overleggen? Neem contact op met het verblijf.",
  call: "Bellen",
  line: "LINE",
  whatsapp: "WhatsApp",
  email: "E-mail",
  payAtProperty: "Betalen bij aankomst",
  payLater: "Online betalen is nog niet mogelijk. Je betaalt {venue} bij aankomst.",
  checkoutTitle: "Je boeking",
  guestDetails: "Wie verblijft er",
  fullName: "Volledige naam",
  phone: "Telefoon",
  phoneHint: "Met landcode, zodat het verblijf je kan bereiken.",
  requests: "Speciale verzoeken",
  requestsHint: "Optioneel. Het verblijf doet wat het kan.",
  confirm: "Boeking bevestigen",
  confirming: "Bezig met boeken…",
  summary: "Je verblijf",
  total: "Totaal",
  dueNow: "Nu te betalen",
  dueAtProperty: "Te betalen bij aankomst",
  agree: "Door te bevestigen ga je akkoord met de annuleringsvoorwaarden van dit tarief. Je gegevens gaan alleen voor deze boeking naar {venue}.",
  confirmedTitle: "Boeking bevestigd",
  confirmedLede: "De details zijn onderweg naar {email}. Laat het boekingsnummer zien bij aankomst.",
  reference: "Boekingsnummer",
  cancelled: "Deze boeking is geannuleerd.",
  anotherStay: "Ander verblijf zoeken",
  bookingMissing: "Boeking niet gevonden. Controleer de link in je bevestigingsmail.",
  backToResults: "Alle verblijven",
  cancelBooking: "Boeking annuleren",
  cancelWarning: "De kamer komt weer te koop en dit kan niet ongedaan worden gemaakt. Er is niets in rekening gebracht.",
  cancelYes: "Ja, annuleren",
  cannotCancel: "Dit tarief kan niet meer online worden geannuleerd. Neem contact op met {venue} om je boeking te wijzigen.",
  cancelledByYou: "Je hebt deze boeking geannuleerd. Er is niets in rekening gebracht.",
  cancelledByVenue: "{venue} heeft deze boeking geannuleerd. Neem contact op als je dit niet verwachtte.",
};

const TEXT: Record<Locale, StaysText> = { en, th, zh, ja, ko, es, fr, de, it, pt, nl };

export function staysText(lang: Locale): StaysText {
  return TEXT[lang] ?? en;
}

/* -------------------------------------------------------------- amenities */

/**
 * The amenity keys market.js allows, in each language. Keys a language lacks
 * fall back to English rather than showing a raw key.
 */
const AMENITY: Record<string, Partial<Record<Locale, string>>> = {
  wifi: { en: "Free Wi-Fi", th: "Wi-Fi ฟรี", zh: "免费 Wi-Fi", ja: "無料Wi-Fi", ko: "무료 Wi-Fi", es: "Wi-Fi gratis", fr: "Wi-Fi gratuit", de: "Kostenloses WLAN", it: "Wi-Fi gratuito", pt: "Wi-Fi grátis", nl: "Gratis wifi" },
  parking: { en: "Parking", th: "ที่จอดรถ", zh: "停车场", ja: "駐車場", ko: "주차", es: "Aparcamiento", fr: "Parking", de: "Parkplatz", it: "Parcheggio", pt: "Estacionamento", nl: "Parkeren" },
  pool: { en: "Swimming pool", th: "สระว่ายน้ำ", zh: "游泳池", ja: "プール", ko: "수영장", es: "Piscina", fr: "Piscine", de: "Pool", it: "Piscina", pt: "Piscina", nl: "Zwembad" },
  restaurant: { en: "Restaurant", th: "ร้านอาหาร", zh: "餐厅", ja: "レストラン", ko: "레스토랑", es: "Restaurante", fr: "Restaurant", de: "Restaurant", it: "Ristorante", pt: "Restaurante", nl: "Restaurant" },
  breakfast: { en: "Breakfast available", th: "มีอาหารเช้า", zh: "提供早餐", ja: "朝食あり", ko: "조식 가능", es: "Desayuno disponible", fr: "Petit-déjeuner disponible", de: "Frühstück erhältlich", it: "Colazione disponibile", pt: "Café da manhã disponível", nl: "Ontbijt beschikbaar" },
  aircon: { en: "Air conditioning", th: "เครื่องปรับอากาศ", zh: "空调", ja: "エアコン", ko: "에어컨", es: "Aire acondicionado", fr: "Climatisation", de: "Klimaanlage", it: "Aria condizionata", pt: "Ar-condicionado", nl: "Airconditioning" },
  garden: { en: "Garden", th: "สวน", zh: "花园", ja: "庭", ko: "정원", es: "Jardín", fr: "Jardin", de: "Garten", it: "Giardino", pt: "Jardim", nl: "Tuin" },
  airport: { en: "Airport transfer", th: "รับส่งสนามบิน", zh: "机场接送", ja: "空港送迎", ko: "공항 픽업", es: "Traslado al aeropuerto", fr: "Navette aéroport", de: "Flughafentransfer", it: "Transfer aeroporto", pt: "Traslado do aeroporto", nl: "Luchthavenvervoer" },
  shuttle: { en: "Shuttle", th: "รถรับส่ง", zh: "班车", ja: "送迎バス", ko: "셔틀", es: "Lanzadera", fr: "Navette", de: "Shuttle", it: "Navetta", pt: "Transfer", nl: "Pendeldienst" },
  laundry: { en: "Laundry", th: "บริการซักรีด", zh: "洗衣服务", ja: "ランドリー", ko: "세탁", es: "Lavandería", fr: "Blanchisserie", de: "Wäscheservice", it: "Lavanderia", pt: "Lavanderia", nl: "Wasserij" },
  kitchen: { en: "Shared kitchen", th: "ครัวส่วนกลาง", zh: "共用厨房", ja: "共用キッチン", ko: "공용 주방", es: "Cocina compartida", fr: "Cuisine partagée", de: "Gemeinschaftsküche", it: "Cucina in comune", pt: "Cozinha compartilhada", nl: "Gedeelde keuken" },
  spa: { en: "Spa & massage", th: "สปาและนวด", zh: "水疗按摩", ja: "スパ・マッサージ", ko: "스파·마사지", es: "Spa y masajes", fr: "Spa et massages", de: "Spa & Massage", it: "Spa e massaggi", pt: "Spa e massagem", nl: "Spa & massage" },
  gym: { en: "Gym", th: "ฟิตเนส", zh: "健身房", ja: "ジム", ko: "피트니스", es: "Gimnasio", fr: "Salle de sport", de: "Fitnessraum", it: "Palestra", pt: "Academia", nl: "Fitnessruimte" },
  family: { en: "Family friendly", th: "เหมาะกับครอบครัว", zh: "适合家庭", ja: "ファミリー向け", ko: "가족 친화", es: "Ideal para familias", fr: "Adapté aux familles", de: "Familienfreundlich", it: "Adatto alle famiglie", pt: "Ideal para famílias", nl: "Gezinsvriendelijk" },
  pets: { en: "Pets allowed", th: "นำสัตว์เลี้ยงเข้าได้", zh: "可携带宠物", ja: "ペット可", ko: "반려동물 동반 가능", es: "Se admiten mascotas", fr: "Animaux acceptés", de: "Haustiere erlaubt", it: "Animali ammessi", pt: "Aceita animais", nl: "Huisdieren toegestaan" },
  frontdesk24: { en: "24-hour front desk", th: "แผนกต้อนรับ 24 ชม.", zh: "24 小时前台", ja: "24時間フロント", ko: "24시간 프런트", es: "Recepción 24 horas", fr: "Réception 24 h/24", de: "24-Stunden-Rezeption", it: "Reception 24 ore", pt: "Recepção 24 horas", nl: "24-uursreceptie" },
  fan: { en: "Fan", th: "พัดลม", zh: "风扇", ja: "扇風機", ko: "선풍기", es: "Ventilador", fr: "Ventilateur", de: "Ventilator", it: "Ventilatore", pt: "Ventilador", nl: "Ventilator" },
  tv: { en: "TV", th: "ทีวี", zh: "电视", ja: "テレビ", ko: "TV", es: "TV", fr: "Télévision", de: "TV", it: "TV", pt: "TV", nl: "Tv" },
  fridge: { en: "Fridge", th: "ตู้เย็น", zh: "冰箱", ja: "冷蔵庫", ko: "냉장고", es: "Nevera", fr: "Réfrigérateur", de: "Kühlschrank", it: "Frigorifero", pt: "Frigobar", nl: "Koelkast" },
  kettle: { en: "Kettle", th: "กาต้มน้ำ", zh: "电热水壶", ja: "電気ケトル", ko: "전기 주전자", es: "Hervidor", fr: "Bouilloire", de: "Wasserkocher", it: "Bollitore", pt: "Chaleira", nl: "Waterkoker" },
  balcony: { en: "Balcony", th: "ระเบียง", zh: "阳台", ja: "バルコニー", ko: "발코니", es: "Balcón", fr: "Balcon", de: "Balkon", it: "Balcone", pt: "Varanda", nl: "Balkon" },
  bathtub: { en: "Bathtub", th: "อ่างอาบน้ำ", zh: "浴缸", ja: "バスタブ", ko: "욕조", es: "Bañera", fr: "Baignoire", de: "Badewanne", it: "Vasca da bagno", pt: "Banheira", nl: "Bad" },
  shower: { en: "Hot shower", th: "น้ำอุ่น", zh: "热水淋浴", ja: "ホットシャワー", ko: "온수 샤워", es: "Ducha caliente", fr: "Douche chaude", de: "Warme Dusche", it: "Doccia calda", pt: "Chuveiro quente", nl: "Warme douche" },
  desk: { en: "Desk", th: "โต๊ะทำงาน", zh: "书桌", ja: "デスク", ko: "책상", es: "Escritorio", fr: "Bureau", de: "Schreibtisch", it: "Scrivania", pt: "Escrivaninha", nl: "Bureau" },
  safe: { en: "Safe", th: "ตู้นิรภัย", zh: "保险箱", ja: "セーフティボックス", ko: "금고", es: "Caja fuerte", fr: "Coffre-fort", de: "Safe", it: "Cassaforte", pt: "Cofre", nl: "Kluis" },
  view: { en: "View", th: "วิวสวย", zh: "景观", ja: "眺望", ko: "전망", es: "Vistas", fr: "Vue", de: "Aussicht", it: "Vista", pt: "Vista", nl: "Uitzicht" },
  kitchenette: { en: "Kitchenette", th: "ครัวเล็ก", zh: "小厨房", ja: "簡易キッチン", ko: "간이 주방", es: "Cocina pequeña", fr: "Kitchenette", de: "Kochnische", it: "Angolo cottura", pt: "Copa", nl: "Kitchenette" },
  terrace: { en: "Terrace", th: "เฉลียง", zh: "露台", ja: "テラス", ko: "테라스", es: "Terraza", fr: "Terrasse", de: "Terrasse", it: "Terrazza", pt: "Terraço", nl: "Terras" },
};

export function amenityLabel(key: string, lang: Locale): string {
  return AMENITY[key]?.[lang] ?? AMENITY[key]?.en ?? key;
}
