import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";
import { buildPageMetadata } from "@/lib/i18n/metadata";
import { localizedPath } from "@/lib/i18n/routing";
import inner from "../../inner.module.css";

export async function generateMetadata({
  params,
}: PageProps<"/[lang]/legal/terms">): Promise<Metadata> {
  const { lang } = await params;
  if (!isLocale(lang)) return {};
  return buildPageMetadata(lang, "/legal/terms", getDictionary(lang).seo.terms);
}

/**
 * English on every locale, for the same reason as the privacy policy: this is
 * the text a court construes, and a translated copy would be a second, subtly
 * different agreement. The heading and navigation stay translated.
 */
export default async function TermsPage({
  params,
}: PageProps<"/[lang]/legal/terms">) {
  const { lang } = await params;
  if (!isLocale(lang)) notFound();

  const t = getDictionary(lang);
  const p = t.legal.terms;

  return (
    <>
      <header className={inner.header}>
        <div className={`wrap ${inner.headerInner}`}>
          <span className="eyebrow">{p.eyebrow}</span>
          <h1 className={inner.h1}>{p.title}</h1>
          <p className={inner.small}>Last updated: [DATE]</p>
        </div>
      </header>

      <section className="section">
        <div className={`wrap ${inner.prose}`}>
          <div className={inner.callout}>
            <strong>Attorney review note:</strong> This draft reflects Thailand
            as the governing law and the Thailand Arbitration Center (THAC) as
            arbitration provider. Please confirm the fully registered company name
            (Thai company registrations typically carry a suffix such as “Co.,
            Ltd.”), fill in the remaining bracketed placeholders (date, notice
            period), and have this document reviewed by a Thailand-licensed
            attorney before publishing.
          </div>

          {lang !== "en" && (
            <p className={inner.small}>
              These Terms are published in English only. Translations elsewhere on
              this site are provided for convenience; the English text is the
              authoritative version.
            </p>
          )}

          <p>
            These Terms of Service (“Terms”) govern your access to and use of
            Reviewslip, including the Reviewslip website, web application, QR
            review slips, AI-assisted drafting features, dashboards, integrations,
            and related services (collectively, the “Service”). The Service is
            provided by Reviewslip (“Reviewslip,” “we,” “us,” or “our”).
          </p>
          <p>
            By creating an Account, purchasing a subscription, accessing, or using
            the Service, you agree to these Terms. If you are using the Service on
            behalf of a business or other organization, you represent that you
            have authority to bind that organization to these Terms, and “you”
            refers to that organization. If you do not agree to these Terms, do
            not use the Service.
          </p>
          <p>
            These Terms incorporate our{" "}
            <Link href={localizedPath(lang, "/legal/privacy")}>Privacy Policy</Link>{" "}
            by reference.
          </p>

          <h2>1. Definitions</h2>
          <ul>
            <li>
              <strong>“Account”</strong> means a registered business user profile
              on the Service.
            </li>
            <li>
              <strong>“AI Draft”</strong> means suggested review or feedback text
              generated by the Service’s AI-assisted drafting features.
            </li>
            <li>
              <strong>“Business Content”</strong> means logos, text, business
              details, links, configurations, categories, and settings that you
              provide to the Service.
            </li>
            <li>
              <strong>“Customer Content”</strong> means selections, phrases,
              comments, ratings, and feedback submitted by an End-Customer through
              a Reviewslip workflow, including any resulting AI Draft and any
              edits an End-Customer makes to it.
            </li>
            <li>
              <strong>“End-Customer”</strong> means an individual who interacts
              with a Reviewslip-generated link, QR code, or landing page in
              connection with a genuine experience with your business, regardless
              of whether that individual creates an Account.
            </li>
            <li>
              <strong>“you” and “your”</strong> mean the business, organization,
              or individual that holds an Account or otherwise directs use of the
              Service, and not an End-Customer, unless the context requires
              otherwise.
            </li>
          </ul>

          <h2>2. Eligibility and accounts</h2>
          <p>
            You must be at least 18 years old and legally capable of entering into
            a binding agreement to use the Service.
          </p>
          <p>
            You are responsible for providing accurate Account information and
            keeping your login credentials secure. You are fully responsible for
            all activity occurring under your Account.
          </p>
          <p>
            You must promptly notify us at{" "}
            <a href="mailto:info@reviewslip.com">info@reviewslip.com</a> if you
            suspect or become aware of any unauthorized access to or use of your
            Account.
          </p>
          <p>
            End-Customers generally do not need to create an Account to submit
            feedback through a Reviewslip link or QR code. The Account-specific
            obligations in this Section 2 apply to business users; other
            provisions of these Terms — including Sections 4 (Lawful and
            Appropriate Use), 5 (Prohibited Activities), 7 (AI-Assisted Drafting
            Features), and our Privacy Policy — govern how End-Customer
            interactions and Customer Content are handled.
          </p>

          <h2>3. The Service</h2>
          <p>
            Reviewslip provides software that helps businesses invite customers
            who have had genuine experiences with the business to provide feedback
            and, where appropriate, draft their own reviews for third-party review
            platforms.
          </p>
          <p>
            Depending on the configuration of the Service, a typical customer
            experience may involve:
          </p>
          <ul>
            <li>Scanning or opening a Reviewslip link or QR code;</li>
            <li>
              Selecting or entering information about their genuine experience;
            </li>
            <li>Receiving an AI Draft based on information they provided;</li>
            <li>Reviewing, editing, and customizing that draft; and</li>
            <li>
              Independently deciding whether, where, and how to post their review.
            </li>
          </ul>
          <p>
            <strong>Important notice:</strong> Reviewslip does not create
            fictitious customer experiences, operate review farms, purchase
            reviews, or automatically publish reviews to third-party review
            platforms on behalf of customers. Reviewslip does not guarantee that a
            customer will write a review, that a review will be published, or that
            a review will remain published.
          </p>

          <h2>4. Lawful and appropriate use</h2>
          <p>
            You may use the Service only for legitimate business purposes and in
            accordance with applicable laws, regulations, and third-party platform
            policies.
          </p>
          <p>
            <strong>Genuine customer requirement:</strong> You agree that review
            invitations generated or distributed through the Service will be
            directed only to individuals who have had a genuine customer
            experience with your business.
          </p>
          <p>
            <strong>Prohibition on review gating:</strong> You must not use the
            Service to selectively solicit reviews based on an expectation that a
            person will leave a positive review, discourage or redirect customers
            from leaving negative reviews, or otherwise manipulate the overall
            sentiment or rating of your reviews.
          </p>
          <p>
            <strong>Compliance:</strong> You must comply with all applicable
            requirements concerning consumer reviews, trade practices, advertising,
            endorsements, privacy, data protection, and marketing communications
            (including FTC guidance on endorsements, testimonials, and reviews, and
            equivalent regional and state laws). You are solely responsible for
            determining which laws and platform rules apply to your business, and
            Reviewslip does not provide legal advice regarding your compliance
            obligations.
          </p>

          <h2>5. Prohibited activities</h2>
          <p>You must not use the Service to:</p>
          <ul>
            <li>
              Create, purchase, sell, generate, or distribute fake, misleading, or
              fabricated reviews;
            </li>
            <li>
              Solicit reviews from individuals who did not have a genuine
              experience with your business;
            </li>
            <li>
              Instruct, incentivize, or pressure customers to leave positive
              reviews or express specific sentiment;
            </li>
            <li>
              Selectively suppress, filter, gate, or discourage negative feedback
              or reviews;
            </li>
            <li>
              Offer money, discounts, free goods, services, loyalty rewards,
              contest entries, or other incentives in exchange for a review where
              prohibited by law or platform policies;
            </li>
            <li>
              Require or pressure a customer to publish an AI Draft without their
              independent review and editing;
            </li>
            <li>
              Instruct customers to include facts, claims, or statements that are
              false or unverified;
            </li>
            <li>
              Ask employees, owners, agents, friends, or family members without a
              genuine customer experience to pose as customers;
            </li>
            <li>
              Create or coordinate multiple accounts or identities to manipulate
              reviews, ratings, or volume;
            </li>
            <li>
              Use bots, scripts, automation, emulators, or unauthorized tools to
              manufacture review activity;
            </li>
            <li>
              Submit, or facilitate the submission of, a review on behalf of or
              purportedly from an individual other than the actual End-Customer
              who had the experience;
            </li>
            <li>
              Solicit reviews for any business other than the business associated
              with your Account without our prior written consent;
            </li>
            <li>Violate a third-party review platform’s terms of service;</li>
            <li>
              Engage in unlawful, fraudulent, deceptive, or abusive activity; or
            </li>
            <li>
              Interfere with, bypass, or attempt to compromise the security or
              operation of the Service.
            </li>
          </ul>
          <p>
            We reserve the right to immediately suspend or terminate any account
            that we reasonably believe is operating in violation of these Terms,
            applicable law, or third-party platform policies.
          </p>

          <h2>6. Third-party review platform policies</h2>
          <p>
            Reviews drafted with assistance from Reviewslip may be submitted by
            customers to third-party platforms (such as Google, Yelp, Facebook, or
            TripAdvisor).
          </p>
          <p>
            <strong>Platform independence:</strong> Those platforms operate
            entirely independently from Reviewslip and maintain their own rules
            regarding review solicitation, content moderation, account suspensions,
            and posting guidelines. Reviewslip is not affiliated with, sponsored
            by, or endorsed by any third-party review platform referenced in the
            Service.
          </p>
          <p>
            <strong>Your responsibility:</strong> You are solely responsible for
            complying with the terms and policies of every platform to which you
            direct customers.
          </p>
          <p>
            <strong>No platform liability:</strong> Reviewslip does not guarantee
            that any third-party platform will accept, publish, retain, or display
            a review. We are not responsible or liable if a platform removes
            reviews, or restricts, suspends, or terminates your business listing,
            profile, or account.
          </p>

          <h2>7. AI-assisted drafting features</h2>
          <p>
            Reviewslip incorporates artificial intelligence to generate suggested
            draft text based strictly on information provided by customer or
            business inputs.
          </p>
          <p>
            <strong>Drafts are suggestions only:</strong> AI Drafts may be
            inaccurate, incomplete, or inconsistent with actual events. AI Drafts
            are non-binding suggestions, not final reviews.
          </p>
          <p>
            <strong>Mandatory customer review:</strong> Customers must retain full
            freedom to review, modify, rewrite, or delete any AI Draft prior to
            publication. Neither you nor Reviewslip may represent an unreviewed AI
            Draft as a customer’s personal statement.
          </p>
          <p>
            <strong>No truth inventions:</strong> You must not use AI features to
            invent false customer experiences, fabricated services, or untrue
            statements.
          </p>
          <p>
            <strong>Published reviews are the End-Customer’s own statements:</strong>{" "}
            Any review an End-Customer chooses to publish, including one based on
            an AI Draft, reflects that End-Customer’s own personal statement.
            Neither you nor Reviewslip may represent it as a statement made by
            Reviewslip or by you.
          </p>
          <p>
            <strong>AI limitations:</strong> AI-generated text is produced by
            automated systems and may contain errors, omissions, or phrasing you
            did not intend. Reviewslip is not responsible for the content an
            End-Customer ultimately chooses to publish.
          </p>

          <h2>8. Customer Content, Business Content, and feedback</h2>
          <p>
            You retain ownership of all Business Content you submit to the Service.
            End-Customers retain ownership of the Customer Content they submit, as
            further described in our Privacy Policy.
          </p>
          <p>
            <strong>License grant:</strong> You grant Reviewslip a worldwide,
            non-exclusive, royalty-free, limited license to host, process,
            reproduce, transmit, display, and adapt Business Content and Customer
            Content solely as necessary to operate, maintain, secure, and improve
            the Service, and as described in our Privacy Policy.
          </p>
          <p>
            <strong>Independent publication:</strong> End-Customers remain
            exclusively responsible for any content they independently choose to
            publish on third-party platforms.
          </p>
          <p>
            <strong>Feedback:</strong> If you or an End-Customer sends us comments,
            suggestions, or ideas about the Service itself (as distinct from
            Customer Content or Business Content), you grant us a perpetual,
            royalty-free license to use that feedback for any purpose, without
            obligation to you.
          </p>

          <h2>9. Representations and warranties</h2>
          <p>
            You represent and warrant that: (a) you have all necessary rights to
            submit Business Content, including any logos or trademarks, and that
            doing so does not infringe any third party’s rights; (b) the
            information in your Business Content is accurate and not misleading;
            and (c) your use of the Service to solicit or manage reviews complies
            with these Terms and all applicable law.
          </p>

          <h2>10. Intellectual property</h2>
          <p>
            The Service — including its software, designs, algorithms, interfaces,
            web applications, branding, logos, documentation, and underlying
            technology — is owned by or licensed to Reviewslip and is protected by
            intellectual property laws.
          </p>
          <p>
            Except for the limited access rights granted under these Terms, no
            ownership rights are transferred to you.
          </p>
          <p>
            You may not copy, modify, reverse engineer, decompile, disassemble,
            resell, distribute, frame, or create derivative works from the Service
            without our express written consent.
          </p>

          <h2>11. Fees, plans, renewals, and payment</h2>
          <p>
            <strong>Subscription fees:</strong> You agree to pay all applicable
            fees for the subscription plan you select. Pricing, billing intervals,
            and features are presented during sign-up or upgrade.
          </p>
          <p>
            <strong>Automatic renewal:</strong> Paid subscriptions automatically
            renew at the end of each billing cycle (for example, monthly or
            annually) unless canceled prior to the renewal date.
          </p>
          <p>
            <strong>Cancellation:</strong> You may cancel your subscription at any
            time through your account dashboard or by contacting{" "}
            <a href="mailto:info@reviewslip.com">info@reviewslip.com</a>.
            Cancellation takes effect at the end of your current paid billing
            period.
          </p>
          <p>
            <strong>Refund policy:</strong> Unless explicitly stated otherwise
            during checkout or required by applicable law, all fees paid are
            non-refundable.
          </p>
          <p>
            <strong>Price changes:</strong> We may change our fees on a prospective
            basis by providing reasonable notice (for example, at least [30] days
            before your next renewal). Continued use of the Service after a price
            change takes effect constitutes acceptance of the new price.
          </p>
          <p>
            <strong>Failed payments and taxes:</strong> You are responsible for
            providing valid payment information. We may suspend or restrict access
            to paid features if payment fails or becomes overdue. All fees are
            exclusive of applicable taxes unless stated otherwise.
          </p>

          <h2>12. Service availability, changes, and force majeure</h2>
          <p>
            We strive to maintain high service uptime, but we do not guarantee
            uninterrupted, secure, or error-free operation.
          </p>
          <p>
            We reserve the right to modify, update, suspend, or discontinue any
            feature, integration, or portion of the Service at any time.
          </p>
          <p>
            We are not liable for outages or disruptions caused by third-party
            infrastructure, including cloud hosting providers, AI infrastructure
            vendors, payment processors, or internet delivery networks.
          </p>
          <p>
            Neither party will be liable for any delay or failure to perform an
            obligation (other than payment obligations) caused by circumstances
            beyond its reasonable control, including acts of God, natural disaster,
            war, terrorism, civil unrest, labor disputes, internet or utility
            failures, or actions of governmental authorities.
          </p>

          <h2>13. Modifications to these Terms</h2>
          <p>
            We may update these Terms from time to time. If we make material
            changes, we will provide notice — such as by posting the updated Terms
            on our website with a revised “Last updated” date, or by emailing the
            address associated with your Account. Updated Terms take effect when
            posted unless stated otherwise. Your continued use of the Service after
            that date constitutes your acceptance of the revised Terms.
          </p>

          <h2>14. Disclaimers</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED ON AN
            “AS IS” AND “AS AVAILABLE” BASIS.
          </p>
          <p>
            REVIEWSLIP EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER
            EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING IMPLIED WARRANTIES
            OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND
            NON-INFRINGEMENT.
          </p>
          <p>
            WITHOUT LIMITING THE FOREGOING, REVIEWSLIP DOES NOT WARRANT OR
            GUARANTEE THAT:
          </p>
          <ul>
            <li>
              THE SERVICE WILL INCREASE YOUR REVIEW COUNT OR IMPROVE YOUR AVERAGE
              RATING;
            </li>
            <li>
              ANY CUSTOMER WILL COMPLETE A REVIEW OR PUBLISH IT TO A THIRD-PARTY
              PLATFORM;
            </li>
            <li>
              REVIEWS WILL BE PUBLISHED, RETAINED, OR PREVENTED FROM REMOVAL BY
              THIRD-PARTY PLATFORMS;
            </li>
            <li>
              THIRD-PARTY PLATFORMS WILL NOT SUSPEND OR PENALIZE YOUR BUSINESS
              LISTING; OR
            </li>
            <li>
              YOUR PARTICULAR USE OF THE SERVICE COMPLIES WITH ALL LAWS OR
              THIRD-PARTY POLICIES APPLICABLE TO YOUR INDUSTRY OR REGION.
            </li>
          </ul>
          <p>
            SOME JURISDICTIONS DO NOT ALLOW CERTAIN WARRANTY DISCLAIMERS, SO SOME
            OF THE ABOVE DISCLAIMERS MAY NOT APPLY TO YOU.
          </p>

          <h2>15. Limitation of liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, REVIEWSLIP AND ITS AFFILIATES,
            OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND LICENSORS WILL NOT BE
            LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE,
            OR EXEMPLARY DAMAGES, OR FOR LOSS OF PROFITS, REVENUE, DATA, GOODWILL,
            BUSINESS OPPORTUNITIES, OR PENALTIES IMPOSED BY THIRD-PARTY PLATFORMS
            OR REGULATORS, ARISING OUT OF OR IN CONNECTION WITH THE SERVICE OR
            THESE TERMS.
          </p>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, REVIEWSLIP’S TOTAL AGGREGATE
            LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE SERVICE OR
            THESE TERMS WILL NOT EXCEED THE GREATER OF: (A) THE TOTAL AMOUNT PAID
            BY YOU TO REVIEWSLIP FOR THE SERVICE IN THE TWELVE (12) MONTHS
            IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM; OR (B) $100
            USD.
          </p>
          <p>
            SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF
            LIABILITY FOR CERTAIN DAMAGES, SO SOME OF THE ABOVE LIMITATIONS MAY NOT
            APPLY TO YOU. NOTHING IN THESE TERMS LIMITS EITHER PARTY’S LIABILITY
            FOR FRAUD, GROSS NEGLIGENCE, OR WILLFUL MISCONDUCT, OR FOR ANY
            LIABILITY THAT CANNOT BE LIMITED UNDER APPLICABLE LAW.
          </p>

          <h2>16. Indemnification</h2>
          <p>
            To the maximum extent permitted by law, you agree to defend, indemnify,
            and hold harmless Reviewslip, its officers, directors, employees,
            contractors, and agents from and against any claims, liabilities,
            damages, losses, judgments, demands, penalties, and expenses (including
            reasonable attorneys’ fees) arising out of or related to:
          </p>
          <ul>
            <li>Your access to or use of the Service;</li>
            <li>Your breach or violation of these Terms;</li>
            <li>
              Your violation of any applicable law, FTC rule, or third-party
              platform policy;
            </li>
            <li>Your Business Content or review solicitation practices; or</li>
            <li>
              Any claims brought by third parties (including your End-Customers or
              review platforms) related to reviews solicited using the Service.
            </li>
          </ul>

          <h2>17. Suspension and termination</h2>
          <p>
            You may stop using the Service and cancel your Account at any time.
          </p>
          <p>
            We reserve the right to suspend or terminate your Account immediately
            if you breach these Terms, use the Service for deceptive or illegal
            practices, fail to pay subscription fees, or if requested by law
            enforcement or regulatory authorities.
          </p>
          <p>
            Upon termination, your right to access the Service ceases immediately.
            We will handle your data as described in our Privacy Policy; you may
            request export of your Business Content for a limited period following
            termination by contacting{" "}
            <a href="mailto:info@reviewslip.com">info@reviewslip.com</a>. Sections
            that by their nature should survive termination will survive, including
            Intellectual Property, Disclaimers, Limitation of Liability,
            Indemnification, and Dispute Resolution.
          </p>

          <h2>18. Governing law and dispute resolution</h2>
          <p>
            These Terms and any dispute arising out of or related to them will be
            governed by and construed in accordance with the laws of Thailand,
            without giving effect to conflict-of-law principles.
          </p>
          <p>
            <strong>Arbitration:</strong> Any dispute arising out of or relating to
            these Terms or the Service will be resolved by binding arbitration
            administered by the Thailand Arbitration Center (THAC) in accordance
            with its Arbitration Rules then in effect. The arbitration will be
            seated in Chiang Mai, Thailand, and conducted in the English language.
            The arbitrator’s award will be final and binding on the parties and may
            be entered as a judgment in any court of competent jurisdiction.
          </p>
          <p>
            <strong>Exceptions:</strong> Either party may (a) bring an individual
            claim in small claims court where available, or (b) seek temporary,
            preliminary, or permanent injunctive relief from the competent courts
            of Chiang Mai, Thailand, to prevent actual or threatened infringement,
            misappropriation, or violation of a party’s intellectual property or
            confidentiality obligations.
          </p>
          <p>
            <strong>No class arbitration:</strong> There is no right or authority
            for any dispute to be brought, heard, or arbitrated as a class,
            collective, or representative action, and the parties waive any right
            to participate in such a proceeding.
          </p>

          <h2>19. Notices</h2>
          <p>
            We may provide notices to you via the email address associated with
            your Account, through in-app messaging, or by posting on our website.
            You may send legal notices to us at{" "}
            <a href="mailto:info@reviewslip.com">info@reviewslip.com</a> or 108 Moo
            8, T. On Tai, San Kamphaeng, Chiang Mai 50130, Thailand.
          </p>

          <h2>20. General provisions</h2>
          <p>
            <strong>Entire agreement:</strong> These Terms, together with our
            Privacy Policy, constitute the entire agreement between you and
            Reviewslip regarding the Service.
          </p>
          <p>
            <strong>Severability:</strong> If any provision is found unenforceable,
            that provision will be modified to reflect the parties’ intention, and
            the remaining provisions will remain in full force.
          </p>
          <p>
            <strong>No waiver:</strong> Failure to enforce any right or provision
            does not constitute a waiver of future enforcement.
          </p>
          <p>
            <strong>Assignment:</strong> You may not assign or transfer these Terms
            without our prior written consent. We may freely assign these Terms in
            connection with a merger, acquisition, or sale of assets.
          </p>
          <p>
            <strong>Relationship of the parties:</strong> The parties are
            independent contractors. Nothing in these Terms creates a partnership,
            joint venture, agency, or employment relationship between you and
            Reviewslip.
          </p>
          <p>
            <strong>Electronic communications:</strong> You consent to receive
            communications from us electronically, and you agree that such
            communications satisfy any legal requirement that they be in writing.
          </p>
          <p>
            <strong>Headings:</strong> Section headings are for convenience only
            and have no interpretive effect.
          </p>

          <h2>21. Contact information</h2>
          <p>
            If you have questions regarding these Terms, please contact us at:
          </p>
          <p>
            Reviewslip
            <br />
            Email: <a href="mailto:info@reviewslip.com">info@reviewslip.com</a>
            <br />
            Address: 108 Moo 8, T. On Tai, San Kamphaeng, Chiang Mai 50130,
            Thailand
          </p>
        </div>
      </section>
    </>
  );
}
